CREATE TABLE IF NOT EXISTS relay.cast_scenes (
    streamer_id bigint NOT NULL REFERENCES relay.users(streamer_id) ON DELETE CASCADE,
    scene_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
    source_id bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN 0 AND 10000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (streamer_id, scene_id),
    CONSTRAINT cast_scenes_source_fk
        FOREIGN KEY (streamer_id, source_id)
        REFERENCES relay.cast_sources(streamer_id, source_id)
        ON DELETE RESTRICT
);
