CREATE TABLE IF NOT EXISTS relay.cast_sources (
    streamer_id bigint NOT NULL REFERENCES relay.users(streamer_id) ON DELETE CASCADE,
    source_id bigint GENERATED BY DEFAULT AS IDENTITY,
    label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 80),
    kind text NOT NULL CHECK (kind IN ('pov', 'camera')),
    ingest_key_hash text NOT NULL UNIQUE CHECK (char_length(ingest_key_hash) = 64),
    ingest_key_enc bytea NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (streamer_id, source_id)
);
